[package]

name = "erya"
version = "0.0.1"
authors = ["tioover <tioover@gmail.com>"]



[lib]
name = "erya"
path = "src/lib.rs"

[dependencies]
num = "*"
glutin = "*"
glium = "*"
time = "*"
rand = "*"
nalgebra = "0.3"
image = "0.4.0"
